# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np

# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

#--------------------KS answer---------------------
print(np.array(weight) / np.array(height)**2 * 730)


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [20]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

#----------------------KS answer-----------------------
def makeMatrix(low, high, shape):
    print(np.random.uniform(low, high, shape))
    
makeMatrix(1,20,(2,5))

[[11.25701312 18.52838062 11.85081388 10.78948164  7.09076129]
 [19.15413441  5.70336911 16.51650246 16.25629604 11.56523424]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons.  Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [21]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [58]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d =','):
    data = np.genfromtxt(filename, delimiter=d, skip_header=1,
                        usecols=np.arange(0,24), invalid_raise = False,
                        names=FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('redsox_2017_hitting.txt')
bs2018 = load_data('redsox_2018_hitting.txt')


#------------------KS Solution: let's figure out who was new on the 2018 team---------

# print(bs2017['Name'])
# print(bs2018['Name'])

players2017 = bs2017['Name'].astype(str)
players2018 = bs2018['Name'].astype(str)

new_players = set(players2018).difference(set(players2017))

print(f'These {len(new_players)} players on the 2018 roster were new to the team: ',
        ', '.join(x for x in new_players))


These 5 players on the 2018 roster were new to the team:  Steve Pearce, Brandon Phillips, Dan Butler, J.D. Martinez, Ian Kinsler
